// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmbri1E5kmudT-UOW6oVZXh_oCO8GsqCc',
    appId: '1:31352400336:android:21478d5fa68272dee0f1d5',
    messagingSenderId: '31352400336',
    projectId: 'mainproject-8de69',
    storageBucket: 'mainproject-8de69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-TRNpYEHXTqJd3H8wacwZpLoQr5ALgM',
    appId: '1:31352400336:ios:009d9150ef31fc9ae0f1d5',
    messagingSenderId: '31352400336',
    projectId: 'mainproject-8de69',
    storageBucket: 'mainproject-8de69.appspot.com',
    iosClientId: '31352400336-of27vppecmerm9cc715odfg5ksas7u5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjmNMACVyQBtuRZEET-kSxAxI-NVllWm4',
    appId: '1:31352400336:web:209a44d23a4be3f7e0f1d5',
    messagingSenderId: '31352400336',
    projectId: 'mainproject-8de69',
    authDomain: 'mainproject-8de69.firebaseapp.com',
    storageBucket: 'mainproject-8de69.appspot.com',
  );

}